### ISSUE TITLE
Error tras la instalación

### ISSUE THREAD

**Issue by alvarosaco** [luckys/RentCarApp#1]
Hola Luis @luckys,

Tras realizar los pasos que detallas para la instalación y después de ejecutar php artisan app:install aparece el error:
> [ErrorException]                                     
> Undefined property: stdClass::$Tables_in_RentCarApp 

Las tablas se crean en la base de datos, pero no se completan con datos de prueba.
¿Qué puede ser? 

Muchas gracias.

**Comment by luckys** [comment]
Hola Alvaro, yo acabo de bajarme el proyecto para probarlo y me funcionó perfectamente, mira a ver que tengas bien configurada la base de datos o bajate otra vez el proyecto no vaya a ser que al bajarse algun archivo se haya corrompido, pero a mi me funciona bien.
saludos

**Comment by alvarosaco** [comment]
<img width="367" alt="captura de pantalla 2015-10-06 a las 15 19 13" src="https://cloud.githubusercontent.com/assets/591409/10321331/aab3fb60-6c3d-11e5-8c6c-0ce8d5fb8e8e.png">

Pienso que la base de datos está correctamente configurada, ya que las tablas se crean. Echando un vistazo al .log el error que indica parece estar relacionado con los permisos a la hora de poblar la base de datos. Aparece en la línea 138 del archivo:
RentCarApp/modules/Auth/Database/Seeders/AuthDatabaseSeeder.php:138

**Comment by luckys** [comment]
Si estas trabajando con linux o mac, mira a ver que tengas todos los permisos, para darle los permisos de forma facil has chmod -R 777 nombre_del_proyecto
