### ISSUE TITLE
Error con modulo User y User de Laravel 

### ISSUE THREAD

**Issue by Mathias88** [luckys/RentCarApp#2]
Buenas, te puedo molestar con una consulta?

Tengo un proyecto en L5.1 que lo empece a migrar a modulos con Ping Pong Sky. Pero me esta dando problemas al querer loguearme a la aplicación.

El error que me esta dando es el siguiente:

FatalErrorException in EloquentUserProvider.php line 126: Class '\App\Modules\User\Entities\User' not found

Como podes ver, esta intentando encontrar el model User en '\App\Modules', cuando lo tendria que buscar en '\Modules'. ¿Que esta pasando?

Los controladores de Auth que vienen en Laravel no los toque, lo unico que hice fue crear un modulo que se llama User, metí todos los controladores a este modulo y apunte los route a estos controladores.

Muchas gracias por tu ayuda!

**Comment by luckys** [comment]
Hola, el error seguramente debe estar en que no has modificado al archivo auth.php de la carpeta config y ahi tendrias que modificar la propiedad model y decirle donde se encuentra la clase User, te quedaria algo como esto:

'model' => Modules\User\Entities\User::class,

y recuerda en el archivo composer agregar esto "Modules\\": "modules/"
me dices si resolvistes el problema.
saludos!!

**Comment by Mathias88** [comment]
Muchas gracias, era un error en el auth.php

**Comment by Albixema** [comment]
hola cuando quiero ejecutar tu aplicacion me sale este mensaje:

  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Incorrect syntax near the keyword 'WHERE'. (
  SQL: SHOW TABLES WHERE Tables_in_Nuevo NOT REGEXP "[[.low-line.]]")

No se si me puedas ayudar

**Comment by luckys** [comment]
Hola Albixema, el problema creo que radica en que estas usando como base de datos Microsoft SQL Server y la siguiente sentencia SHOW TABLES WHERE Tables_in_Nuevo NOT REGEXP "[[.low-line.]]") solo la he probado con mysql, con lo cual es posible que si usas otro gestor no funcione.
saludos

**Comment by Albixema** [comment]
Oh muchas gracias y no sabes cual seria la instruccion con sql server?

**Comment by saezfernando** [comment]
Hola, estoy tratando de hacer andar tu app y cuando ejecuto el install me tira problemas con en la sentencia SHOW TABLES WHERE Tables_in_Nuevo NOT REGEXP "[[.low-line.]]"). Estoy usando laravel 5.2 y MySQL 5.7.
Saludos
